name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm ci
      working-directory: ./client

    - name: Run Tests
      run: npm test -- --watchAll=false
      working-directory: ./client

    - name: Build App
      run: npm run build
      working-directory: ./client

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: client-build
        path: ./client/build
